dosfstools/dosfstools

src/fat.c
To fix this:
```
Starting check/repair pass.
FATs differ but appear to be intact.1) Use first FAT
2) Use second FAT
[12?q]? 
```
=> add missing \n

src/fatlabel.c
* Do not allow specifying empty argument as volume ID
* Check for errno (as general error) after more specific errors
Fixes #64
=> fatlabel: Fix parsing volume ID

src/check.c
mtools writes uninitialized data to the case field of some
directory entries. Running fsck.fat on these filesystems
will cause the directory to get deleted which can lead to
data loss. Detect this situation and clear the flag instead.
mtools patch to fix the original issue:
https://lists.gnu.org/archive/html/info-mtools/2014-08/msg00000.html
Signed-off-by: Will Newton <willn@resin.io>
=> src/check.c: Fix up mtools created bad dir entries

src/check.c, src/file.c, src/mkfs.fat.c
In commit 51da71a is partial fix for handling leading 0xE5 byte. But fix is not complete, on another two places it needs to be done. In fsck.fat when converting file name entry from FAT directory and in mkfs.fat when writing label to FAT directory.
=> Fix commit 51da71a - Handle conversion between 0xe5 and 0x05

manpages/fatlabel.8.in, manpages/fsck.fat.8.in, src/Makefile.am, src/boot.c, src/boot.h, src/charconv.c, src/charconv.h, src/fatlabel.c
* Initialize only LC_CTYPE locale
* Initialize iconv "from codepage" with //TRANSLIT
* fsck.fat: Change default DOS codepage to 850
* fatlabel: Add support for --codepage option
* manpages: Add section DOS CODEPAGES to fatlabel
See also: https://github.com/dosfstools/dosfstools/issues/66
=> Codepage support for fsck.fat and fatlabel

manpages/fatlabel.8.in, manpages/mkfs.fat.8.in, src/Makefile.am, src/common.c, src/common.h, src/fatlabel.c, src/mkfs.fat.c
For mkfs.fat also adds support for specifying --codepage.
See also: https://github.com/dosfstools/dosfstools/issues/66
=> Check for valid label in mkfs.fat and fatlabel

src/boot.c, src/check.c, src/common.c, src/mkfs.fat.c
**fsck.fat**: Do not use `time_t` type and `strftime()` function which are affected by the Year 2038 Bug. Instead parse date/time directly from DOS format which avoids conversion from DOS to UNIX + conversion from UNIX to string.
**mkfs.fat**: Check return values of `time()`, `gmtime()` and `localtime()` function which may fail. Fallback to date/time 1.1.1980 00:00:00 when those functions fail. For generating volume id, add fallback code based on `rand()` function.
=> Year 2038 problem

src/mkfs.fat.c
Global variable hidden_sectors is in host byte order.
=> mkfs.fat: Fix endianity for hidden_sectors

src/fat.c, src/fat.h, src/fatlabel.c, src/fsck.fat.c
Function read_fat() allocates memory to the user supplied buffer. Therefore
that function needs complement function for releasing allocated memory and
user needs to call if after finish its work.
This patch fixes memory leaks in fsck.fat and fatlabel tools.
Fixes #13
=> Fix memory leaks in read_fat() function

src/charconv.c, src/charconv.h
The function local_string_to_dos_string is vulnerable to an off-by-one
buffer overflow. In fact, it is triggered in default usage and becomes
visible when compiled with ASAN:
$ CFLAGS="-fsanitize=address" ./configure
$ dd if=/dev/zero of=example.iso bs=1024 seek=64 count=1
$ ./src/mkfs.fat example.iso
mkfs.fat 4.1+git (2017-01-24)
=================================================================
==3857==ERROR: AddressSanitizer: stack-buffer-overflow on address ...
The problem is that the argument "len" to local_string_to_dos_string
stores the length of the output buffer. Yet it can also be used as an
index to store '\0':
If the whole "out" buffer has been written to, bytes_out is 0 and
the assignment in out[len-bytes_out] therefore leads to an off-by-one.
Signed-off-by: Tobias Stoeckmann …
=> Fixed off-by-one in local_string_to_dos_string.

.travis.yml, tests/test-fsck, tests/test-label, tests/test-mkfs
* Use both gcc and clang compilers
* Compile with -fwrapv and -fsanitize=address
* Compile in both 32 and 64 modes for x86 systems
* Cross compile for little endian arm and big endian powerpc
* Run cross compiled binaries in qemu
=> Update Travis configuration

src/device_info.c, src/fatlabel.c, src/mkfs.fat.c
Properly handle errors from strtoul() function. To detect overflow/underflows it is needed to check for errno. Also there is a need to check special case if argument is empty string.
=> mkfs.fat: Fix parsing and validation of numeric values

src/lfn.c
Not sure if this needs to be inlined, but I made it `inline` to match the existing macro.
=> Use static inline function instead of statement expression

.travis.yml
I won't pretend to understand why, but getting iconv config from the platform's libc causes segfault.
This PR Fixes #130
=> Fix dynamically linked PPC & ARM travis builds

src/mkfs.fat.c
Original author H. Peter Anvin allowed to put mkfs.fat boot sector code
into the public domain.
Closes: #18
=> mkfs.fat: Clarify licensing of the dummy boot sector

src/mkfs.fat.c
Let's make sure to sync the block device, before exiting. Otherwise, if
we operate on a loop device and people issue "losetup -d" right after
this command finishes our in-flight writes might never hit the disk.
(This took 4h of my life for me to figure out. The mkfs for all other
file systems I tested appear to synchronize when done, hence fat should
do too.)
=> mkfs: fsync() the block device before exiting

src/boot.c, src/charconv.c, src/charconv.h, src/file.c
Fix fallback translit code and add internal CP850 translit table. Fix buffer overflows by specifying output buffer size. Fix usage of iconv() function and use ICONV_CONST autoconf macro.
=> More fixes for charconv code

src/boot.c, src/boot.h, src/fsck.fat.c, src/fsck.fat.h, src/mkfs.fat.c
DOS Clean Shutdown bit in first reserved FAT entry is cleared when DOS or
Windows FAT driver mounts a volume and set is back when doing unmount.
Therefore set this bit when clearing FAT dirty bit in boot sector.
Fixes: #38
=> fsck.fat: Check for DOS Clean Shutdown bit

manpages/mkfs.fat.8.in
BLOCK-COUNT is always in KiB unit independently of the disk sector size,
FAT sector size or FAT cluster size.
=> Clarify unit of BLOCK-COUNT in mkfs.fat manpage

manpages/fatlabel.8.in, manpages/fsck.fat.8.in, manpages/mkfs.fat.8.in
Fix formatting of hyphens, en and em dashes, emphases, bullets and fix switching to previous font style.
In troff manpage language ascii minus is written as `\-`, mathematical minus as `\(mi`, hyphen as `-`, en-dash as `\(en`, em-dash as `\(em` and bullet as `\(bu`. Previous font style is selected by `\fP`.
=> Fix formatting manpages

README, README.md, configure.ac, src/Makefile.am, src/device_info.c, src/testdevinfo.c
There is no need that mkfs.fat depends on systemd. It uses it only for
reading additional information about block device.
This patch replace systemd/udev dependency code by reading those additional
information about block device directly from sysfs.
So no functionality of mkfs.fat is lost or removed.
=> mkfs.fat: Remove dependency on systemd/udev

manpages/mkfs.fat.8.in, src/mkfs.fat.c
Allow to specify also second hard disk (0x81) or second floppy device
(0x01) as -D option = BIOS drive number.
=> mkfs.fat: Relax -D option (BIOS drive number)

src/boot.c
This allows the FSIBOOT stage of lDOS boot32.asm to remain
in the FSINFO sector even when the info entries are reset.
I reviewed several sources to determine whether we are in the right to
assume that the reserved 480 bytes used by FSIBOOT should be preserved
by drivers updating the FSINFO entry fields.
Quoting the document "Microsoft Extensible Firmware Initiative - FAT32
File System Specification - FAT: General Overview of On-Disk Format -
Version 1.03, December 6, 2000" on these bytes:
> [Name] FSI_Reserved1
>
> [Offset (byte)] 4
>
> [Size (bytes)] 480
>
> [Description] This field is currently reserved for future expansion.
> FAT32 format code should always initialize all bytes of this field
> to 0. Bytes in this field must currently never be used.
This specifically states that "FAT32 …
=> fsck.fat: preserve info sector reserved fields

manpages/fsck.fat.8.in, src/check.c, tests/Makefile.am
This change makes fsck.fat check whether `.` and `..` entries exist in all non-root directories as the in two very first. If those entries are occupied by some other file, fsck.fat will offer to move them to some later slot. `.` and `..` entries found in any other slots are treated as ordinary bad-shortname entries. The test case for this situation has been enabled and verified to perform as expected.
The function `drop_file()` was also modified so that it does not mark dropped file clusters as free. This was necessary because otherwise dropping too-late `.` and `..` entries would delete their containing directory. If deleted entries' clusters are truly no longer used, they shall be picked up by a later reclamation stage.
Additionally, `subdirs()` and `check_file()` were modified not to …
=> fsck.fat: properly check for valid "." and ".." entries

manpages/fsck.fat.8.in, src/boot.c, src/boot.h, src/charconv.c, src/charconv.h, src/check.c, src/check.h, src/common.c, src/common.h, src/fatlabel.c, src/fsck.fat.c, src/fsck.fat.h, src/mkfs.fat.c
Checks the volume label from the root directory entry that is valid and
matches the label stored in boot sector.
=> fsck.fat: Check and fix label

src/boot.c, src/check.c, src/fat.c, src/fsck.fat.h, src/mkfs.fat.c
In dosfstools codebase is primary used `unsigned long long` type for 64bit integers and on few places `uint64_t`. So replace `uint64_t` by `unsigned long long` type and fix some casting problems around.
=> Use unsigned long long type instead of uint64_t

src/boot.c, src/common.c, src/mkfs.fat.c, tests/test-mkfs
Hi,
Here are some patches that implement reproducible builds with the SOURCE_DATE_EPOCH variable (in the context of dosfstools being used as part of builds).
I've run the test suite and it passes.
=> Use SOURCE_DATE_EPOCH for reproducible builds

configure.ac, src/blkdev/blkdev.c, src/device_info.c
This is the same as #158 but based on master and includes the required change of configure.ac (https://github.com/dosfstools/dosfstools/pull/158#issuecomment-770943078) to avoid build failure on Debian 10
Fixes: #158
Fixes: #159
=> Fix building on macos

src/common.c
char may be either signed or unsigned and if it is signed the "< 0x20"
comparison will reject any values >= 0x80 even though these are valid
characters in a label.
Cast to an unsigned type to ensure the full range of valid characters
are accepted.
=> fatlabel: fix range check for signed characters

src/fatlabel.c, src/fsck.fat.c, src/mkfs.fat.c
Use last given codepage argument instead of first to comply with other command line arguments.
Proof of Concept:
1. Prepare a filesystem with label ° in codepage 1252
```
$ dd if=/dev/zero of=poc.iso bs=512 count=100
$ mkfs.fat -c 1252 -n "°" poc.iso
```
2. Query the label
```
$ fatlabel -c 1252 poc.iso
$ fatlabel -c 850 -c 1252 poc.iso
```
The output should be identical.
Signed-off-by: Samanta Navarro <ferivoz@riseup.net>
=> Support multiple codepage command line arguments.

src/fatlabel.c
Fixes a compiler error that can occur when building with clang: `error: variable 'change' is used uninitialized whenever 'if' condition is false [-Werror,-Wsometimes-uninitialized]`
Previously, this variable was initialized on all code paths except for one that called `usage(1, 1)`.  In practice that should have been safe as `usage` should cause the program to exit.  But to make this obviously safe, initialize `change` to false when it is declared.
=> fatlabel: Fix a compiler warning about a maybe-unitialized variable

src/mkfs.fat.c
I have reworked the bad block processing in mkfs.fat:
- Use nicer error messages when encountering negative values in badblocks file
- Prevent signed integer overflow with excessively huge badblocks file
- Correctly count amount of bad blocks specified in badblocks file
Feel free to cherry pick commits which look good to you. You can find two proof of concepts in the commit messages to see the differences.
=> mkfs.fat: nicer bad block messages

src/boot.c
If a file has to be generated, then alloc_rootdir_entry tries to create a unique name by using a counter curr_num for name generation and looking for duplicates. If no duplicate is found, the counter curr_num is not incremented, which means that the next file uses the same name again. It is only incremented after the previously created file is detected, just to repeat the loop again.
The improvement is simple: Increment the counter after creating the filename. This has also the benefit that the check and use of curr_num are closer to each other within the source code.
=> fsck.fat: Reduce duplicate file name lookups

src/mkfs.fat.c
The blkbuf array in check_blocks is not needed. It is always given as an argument to do_check. Keep the buffer there for easier access and reduced visibility in code.
=> mkfs.fat: Reduce visibility of static buffer
